name: Deploy

run-name: Deploy

on: workflow_call

concurrency:
  group: 'deploy'
  cancel-in-progress: true

permissions:
  pages: write
  id-token: write
  actions: read

jobs:
  deploy:
    environment:
      name: github-pages

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: 'gh-pages'

      - name: Setup Pages
        uses: actions/configure-pages@v4
        with:
          enablement: true
          token: ${{ secrets.GH_TOKEN }}

      - name: Build GH Pages Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './'

      - name: Publish to GH Pages
        uses: actions/deploy-pages@v4
